name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 检查
    - name: Checkout
      uses: actions/checkout@v2

    # 登陆
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: <registry>
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 创建 Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: <registry>/<username>/<repository>:${{ github.sha }}

    # 部署到服务器
    - name: SSH into remote server and deploy Docker image
      uses: appleboy/ssh-action@master
      env:
        DOCKER_IMAGE: <registry>/<username>/<repository>:${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker pull $DOCKER_IMAGE
          docker stop rsr || true
          docker rm rsr || true
          docker run -d --name rsr -p 80:80 $DOCKER_IMAGE